### ISSUE TITLE
File drop not working

### ISSUE THREAD

**Issue by joshpunb** [raphaelchenouard/ibex-manifold-explorer#1]
I'm trying to run this, but the file drop feature doesn't seem to work for me. I've tried Chrome and Firefox. Do I need to enable something on the web browser?

**Comment by jeanrhum** [comment]
Which version of ibex are you using? and which version of manifold format is used?
I use v2 format of ibex manifold. I see that in current sources, the V4 format is used. I will update soon to this format.

**Comment by raphaelchenouard** [comment]
Which version of ibex and manifold format do you use?
Currently, the supported version of manifold format is v2 but I see that v4 is used in latest source. I will make an apdate very soon.

**Comment by raphaelchenouard** [comment]
v4 format is now supported.
